#!/bin/bash
ROFI_OPTIONS=(-theme $HOME/.config/rofi/rofi_full -m 0 -fullscreen)

another=$(echo "GOOGLE
CONFIGS
SCRIPTS
SHELL
SOUND
VIDEO" | awk '{print $(NF-1)}' | rofi "${ROFI_OPTIONS[@]}" -dmenu -i -p "  ")



browse(){
	selected=$(ls "$1/" | rofi "${ROFI_OPTIONS[@]}" -dmenu -p "  $1/")
	[[ -z $selected ]] && exit
	if [[ -f $1/$selected ]]; then
		code $1/$selected
	elif [[ -d $1/$selected ]]; then
		browse $1/$selected
	else
		touch $1/$selected
		chmod +x $1/$selected
		code $1/$selected
	fi
}



if [ "$another" == "SHELL" ] ; then
	selected=$(echo ".zshrc
.Xresources
.bashrc
.tmux.conf
.bashrc.aliases
.Xmodmap" | rofi "${ROFI_OPTIONS[@]}" -dmenu -p "  ~/")
	[[ -z $selected ]] && exit
	code "$HOME/$selected";

elif [ "$another" == "CONFIGS" ] ; then
	browse ~/.config;

elif [ "$another" == "SCRIPTS" ] ; then
	browse ~/develop/scripts;
	
elif [ "$another" == "GOOGLE" ] ; then
	rofi "${ROFI_OPTIONS[@]}" -dmenu -p "  " | xargs -I{} xdg-open https://www.google.com/search?q={} ;

elif [ "$another" == "SOUND" ] ; then
	pavucontrol;

elif [ "$another" == "VIDEO" ] ; then
	arandr;

else
    echo $another
fi